/**
 * Vermont Zip Code Database
 * Maps zip codes to cities and counties
 */

export interface ZipCodeData {
  zip: string;
  type: string;
  cities: string[];
  county: string;
  areaCodes: string[];
}

export const vermontZipCodes: ZipCodeData[] = [
  { zip: '05001', type: 'Standard', cities: ['White River Junction', 'White Riv Jct'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05009', type: 'Unique', cities: ['White River Junction', 'White Riv Jct'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05030', type: 'PO Box', cities: ['Ascutney'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05031', type: 'PO Box', cities: ['Barnard'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05032', type: 'Standard', cities: ['Bethel'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05033', type: 'Standard', cities: ['Bradford'], county: 'Orange', areaCodes: ['603', '802'] },
  { zip: '05034', type: 'Standard', cities: ['Bridgewater'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05035', type: 'Standard', cities: ['Bridgewater Corners', 'Brdgewtr Cors', 'Bridgewtr Cor'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05036', type: 'Standard', cities: ['Brookfield'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05037', type: 'Standard', cities: ['Brownsville'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05038', type: 'Standard', cities: ['Chelsea'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05039', type: 'Standard', cities: ['Corinth'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05040', type: 'Standard', cities: ['East Corinth'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05041', type: 'Standard', cities: ['East Randolph'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05042', type: 'Standard', cities: ['East Ryegate', 'Ryegate'], county: 'Caledonia', areaCodes: ['603', '802'] },
  { zip: '05043', type: 'Standard', cities: ['East Thetford'], county: 'Orange', areaCodes: ['603', '802'] },
  { zip: '05045', type: 'Standard', cities: ['Fairlee'], county: 'Orange', areaCodes: ['603', '802'] },
  { zip: '05046', type: 'Standard', cities: ['Groton'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05047', type: 'PO Box', cities: ['Hartford'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05048', type: 'Standard', cities: ['Hartland'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05049', type: 'PO Box', cities: ['Hartland Four Corners', 'Hartland Cors'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05050', type: 'PO Box', cities: ['Mc Indoe Falls', 'Mc Indoe Fls', 'Mcindoe Falls'], county: 'Caledonia', areaCodes: ['603', '802'] },
  { zip: '05051', type: 'Standard', cities: ['Newbury'], county: 'Orange', areaCodes: ['603', '802'] },
  { zip: '05052', type: 'Standard', cities: ['North Hartland', 'N Hartland'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05053', type: 'Standard', cities: ['North Pomfret', 'Pomfret'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05054', type: 'PO Box', cities: ['North Thetford', 'N Thetford'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05055', type: 'Standard', cities: ['Norwich'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05056', type: 'Standard', cities: ['Plymouth'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05058', type: 'Standard', cities: ['Post Mills'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05059', type: 'PO Box', cities: ['Quechee'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05060', type: 'Standard', cities: ['Randolph', 'Braintree', 'W Brookfield', 'West Brookfield'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05061', type: 'Standard', cities: ['Randolph Center', 'Randolph Ctr'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05062', type: 'Standard', cities: ['Reading'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05065', type: 'Standard', cities: ['Sharon'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05067', type: 'Standard', cities: ['South Pomfret', 'Pomfret'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05068', type: 'Standard', cities: ['South Royalton', 'Pomfret', 'S Royalton'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05069', type: 'Standard', cities: ['South Ryegate'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05070', type: 'Standard', cities: ['South Strafford', 'S Strafford'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05071', type: 'Standard', cities: ['South Woodstock', 'S Woodstock'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05072', type: 'Standard', cities: ['Strafford'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05073', type: 'Standard', cities: ['Taftsville'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05074', type: 'PO Box', cities: ['Thetford'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05075', type: 'Standard', cities: ['Thetford Center', 'Thetford Ctr'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05076', type: 'Standard', cities: ['Topsham', 'East Corinth'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05077', type: 'Standard', cities: ['Tunbridge'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05079', type: 'Standard', cities: ['Vershire'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05081', type: 'Standard', cities: ['Wells River'], county: 'Orange', areaCodes: ['603', '802'] },
  { zip: '05083', type: 'Standard', cities: ['West Fairlee'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05084', type: 'Standard', cities: ['West Hartford', 'Pomfret'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05085', type: 'PO Box', cities: ['West Newbury'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05086', type: 'Standard', cities: ['West Topsham', 'East Orange'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05088', type: 'PO Box', cities: ['Wilder'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05089', type: 'Standard', cities: ['Windsor', 'West Windsor'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05091', type: 'Standard', cities: ['Woodstock'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05101', type: 'Standard', cities: ['Bellows Falls'], county: 'Windham', areaCodes: ['603', '802'] },
  { zip: '05141', type: 'Standard', cities: ['Cambridgeport'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05142', type: 'Standard', cities: ['Cavendish'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05143', type: 'Standard', cities: ['Chester', 'Andover', 'Athens', 'Baltimore'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05144', type: 'PO Box', cities: ['Chester Depot', 'Chester'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05146', type: 'Standard', cities: ['Grafton'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05148', type: 'Standard', cities: ['Londonderry', 'Landgrove'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05149', type: 'Standard', cities: ['Ludlow'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05150', type: 'Standard', cities: ['North Springfield', 'N Springfield'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05151', type: 'Standard', cities: ['Perkinsville'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05152', type: 'Standard', cities: ['Peru'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05153', type: 'Standard', cities: ['Proctorsville', 'South Reading'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05154', type: 'Standard', cities: ['Saxtons River'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05155', type: 'Standard', cities: ['South Londonderry', 'S Londonderry', 'Stratton Mnt', 'Stratton Mo...'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05156', type: 'Standard', cities: ['Springfield'], county: 'Windsor', areaCodes: ['603', '802'] },
  { zip: '05158', type: 'Standard', cities: ['Westminster'], county: 'Windham', areaCodes: ['603', '802'] },
  { zip: '05159', type: 'PO Box', cities: ['Westminster Station', 'Westmnstr Sta'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05161', type: 'Standard', cities: ['Weston'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05201', type: 'Standard', cities: ['Bennington', 'Woodford'], county: 'Bennington', areaCodes: ['518', '802', '838'] },
  { zip: '05250', type: 'Standard', cities: ['Arlington', 'Sandgate', 'Sunderland', 'West Arlingtn', 'Wes...'], county: 'Bennington', areaCodes: ['518', '802', '838'] },
  { zip: '05251', type: 'Standard', cities: ['Dorset'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05252', type: 'Standard', cities: ['East Arlington', 'E Arlington'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05253', type: 'Standard', cities: ['East Dorset'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05254', type: 'PO Box', cities: ['Manchester'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05255', type: 'Standard', cities: ['Manchester Center', 'Manchestr Ctr'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05257', type: 'Standard', cities: ['North Bennington', 'N Bennington'], county: 'Bennington', areaCodes: ['518', '802', '838'] },
  { zip: '05260', type: 'Standard', cities: ['North Pownal'], county: 'Bennington', areaCodes: ['518', '802', '838'] },
  { zip: '05261', type: 'Standard', cities: ['Pownal'], county: 'Bennington', areaCodes: ['413', '518', '802', '838'] },
  { zip: '05262', type: 'Standard', cities: ['Shaftsbury'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05301', type: 'Standard', cities: ['Brattleboro', 'Dummerston', 'Guilford', 'W Brattleboro', 'Wes...'], county: 'Windham', areaCodes: ['413', '603', '802'] },
  { zip: '05302', type: 'PO Box', cities: ['Brattleboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05303', type: 'PO Box', cities: ['Brattleboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05304', type: 'PO Box', cities: ['Brattleboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05340', type: 'Standard', cities: ['Bondville', 'Winhall'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05341', type: 'Standard', cities: ['East Dover', 'Dover'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05342', type: 'Standard', cities: ['Jacksonville'], county: 'Windham', areaCodes: ['413', '802'] },
  { zip: '05343', type: 'Standard', cities: ['Jamaica'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05344', type: 'PO Box', cities: ['Marlboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05345', type: 'Standard', cities: ['Newfane', 'Brookline'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05346', type: 'Standard', cities: ['Putney', 'E Dummerston', 'East Dummerston', 'Westminst...'], county: 'Windham', areaCodes: ['603', '802'] },
  { zip: '05350', type: 'Standard', cities: ['Readsboro'], county: 'Bennington', areaCodes: ['413', '802'] },
  { zip: '05351', type: 'Standard', cities: ['South Newfane'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05352', type: 'Standard', cities: ['Stamford', 'Readsboro'], county: 'Bennington', areaCodes: ['413', '802'] },
  { zip: '05353', type: 'Standard', cities: ['Townshend'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05354', type: 'Standard', cities: ['Vernon'], county: 'Windham', areaCodes: ['413', '603', '802'] },
  { zip: '05355', type: 'Standard', cities: ['Wardsboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05356', type: 'Standard', cities: ['West Dover', 'Mount Snow'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05357', type: 'PO Box', cities: ['West Dummerston', 'W Dummerston'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05358', type: 'Standard', cities: ['West Halifax'], county: 'Windham', areaCodes: ['413', '802'] },
  { zip: '05359', type: 'Standard', cities: ['West Townshend', 'W Townshend', 'Windham'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05360', type: 'Standard', cities: ['West Wardsboro', 'Stratton', 'W Wardsboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05361', type: 'Standard', cities: ['Whitingham'], county: 'Windham', areaCodes: ['413', '802'] },
  { zip: '05362', type: 'Standard', cities: ['Williamsville'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05363', type: 'Standard', cities: ['Wilmington', 'Searsburg', 'West Marlboro'], county: 'Windham', areaCodes: ['802'] },
  { zip: '05401', type: 'Standard', cities: ['Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05402', type: 'PO Box', cities: ['Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05403', type: 'Standard', cities: ['South Burlington', 'S Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05404', type: 'Standard', cities: ['Winooski'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05405', type: 'Unique', cities: ['Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05406', type: 'PO Box', cities: ['Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05407', type: 'PO Box', cities: ['South Burlington', 'S Burlington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05408', type: 'Standard', cities: ['Burlington'], county: 'Chittenden', areaCodes: ['518', '802', '838'] },
  { zip: '05439', type: 'Unique', cities: ['Colchester'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05440', type: 'Standard', cities: ['Alburgh', 'Alburg'], county: 'Grand Isle', areaCodes: ['354', '450', '518', '579', '802', '838'] },
  { zip: '05441', type: 'Standard', cities: ['Bakersfield'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05442', type: 'Standard', cities: ['Belvidere Center', 'Belvidere Ctr'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05443', type: 'Standard', cities: ['Bristol', 'Lincoln'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05444', type: 'Standard', cities: ['Cambridge'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05445', type: 'Standard', cities: ['Charlotte'], county: 'Chittenden', areaCodes: ['518', '802', '838'] },
  { zip: '05446', type: 'Standard', cities: ['Colchester'], county: 'Chittenden', areaCodes: ['518', '802', '838'] },
  { zip: '05447', type: 'Standard', cities: ['East Berkshire', 'E Berkshire'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05448', type: 'Standard', cities: ['East Fairfield', 'E Fairfield'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05449', type: 'PO Box', cities: ['Colchester'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05450', type: 'Standard', cities: ['Enosburg Falls', 'Enosburg Fls'], county: 'Franklin', areaCodes: ['354', '450', '579', '802'] },
  { zip: '05451', type: 'PO Box', cities: ['Essex'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05452', type: 'Standard', cities: ['Essex Junction', 'Essex Jct'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05453', type: 'PO Box', cities: ['Essex Junction', 'Essex Jct'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05454', type: 'Standard', cities: ['Fairfax'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05455', type: 'Standard', cities: ['Fairfield', 'Sheldon'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05456', type: 'Standard', cities: ['Ferrisburgh'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05457', type: 'Standard', cities: ['Franklin'], county: 'Franklin', areaCodes: ['354', '450', '579', '802'] },
  { zip: '05458', type: 'Standard', cities: ['Grand Isle'], county: 'Grand Isle', areaCodes: ['518', '802', '838'] },
  { zip: '05459', type: 'Standard', cities: ['Highgate Center', 'Highgate Ctr'], county: 'Franklin', areaCodes: ['354', '450', '579', '802'] },
  { zip: '05460', type: 'PO Box', cities: ['Highgate Springs', 'Highgate Sprg'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05461', type: 'Standard', cities: ['Hinesburg'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05462', type: 'Standard', cities: ['Huntington'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05463', type: 'Standard', cities: ['Isle La Motte'], county: 'Grand Isle', areaCodes: ['518', '802', '838'] },
  { zip: '05464', type: 'Standard', cities: ['Jeffersonville', 'Jeffersonvlle'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05465', type: 'Standard', cities: ['Jericho', 'Jericho Center', 'Jericho Ctr'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05466', type: 'PO Box', cities: ['Jonesville'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05468', type: 'Standard', cities: ['Milton'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05469', type: 'PO Box', cities: ['Monkton'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05470', type: 'PO Box', cities: ['Montgomery'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05471', type: 'Standard', cities: ['Montgomery Center', 'Montgomry Ctr'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05472', type: 'Standard', cities: ['New Haven'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05473', type: 'Standard', cities: ['North Ferrisburgh', 'N Ferrisburgh'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05474', type: 'Standard', cities: ['North Hero'], county: 'Grand Isle', areaCodes: ['518', '802', '838'] },
  { zip: '05476', type: 'Standard', cities: ['Richford'], county: 'Franklin', areaCodes: ['354', '450', '579', '802'] },
  { zip: '05477', type: 'Standard', cities: ['Richmond', 'Bolton Valley'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05478', type: 'Standard', cities: ['Saint Albans'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05479', type: 'Unique', cities: ['Essex Junction', 'Essex Jct'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05481', type: 'PO Box', cities: ['Saint Albans Bay', 'St Albans Bay'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05482', type: 'Standard', cities: ['Shelburne'], county: 'Chittenden', areaCodes: ['518', '802', '838'] },
  { zip: '05483', type: 'Standard', cities: ['Sheldon'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05485', type: 'PO Box', cities: ['Sheldon Springs', 'Sheldon Spgs'], county: 'Franklin', areaCodes: ['802'] },
  { zip: '05486', type: 'Standard', cities: ['South Hero'], county: 'Grand Isle', areaCodes: ['518', '802', '838'] },
  { zip: '05487', type: 'Standard', cities: ['Starksboro'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05488', type: 'Standard', cities: ['Swanton'], county: 'Franklin', areaCodes: ['354', '450', '579', '802'] },
  { zip: '05489', type: 'Standard', cities: ['Underhill'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05490', type: 'PO Box', cities: ['Underhill Center', 'Underhill Ctr'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05491', type: 'Standard', cities: ['Vergennes', 'Addison', 'Panton'], county: 'Addison', areaCodes: ['518', '802', '838'] },
  { zip: '05492', type: 'Standard', cities: ['Waterville'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05494', type: 'Standard', cities: ['Westford'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05495', type: 'Standard', cities: ['Williston', 'Saint George', 'St George'], county: 'Chittenden', areaCodes: ['802'] },
  { zip: '05601', type: 'PO Box', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05602', type: 'Standard', cities: ['Montpelier', 'Berlin', 'Middlesex', 'Middlesex Center', 'Mid...'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05603', type: 'Unique', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05604', type: 'Unique', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05609', type: 'Unique', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05620', type: 'Unique', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05633', type: 'Unique', cities: ['Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05640', type: 'Standard', cities: ['Adamant'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05641', type: 'Standard', cities: ['Barre', 'Orange'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05647', type: 'Standard', cities: ['Cabot'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05648', type: 'Standard', cities: ['Calais'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05649', type: 'Standard', cities: ['East Barre'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05650', type: 'Standard', cities: ['East Calais'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05651', type: 'Standard', cities: ['East Montpelier', 'E Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05652', type: 'Standard', cities: ['Eden'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05653', type: 'Standard', cities: ['Eden Mills', 'Eden'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05654', type: 'Standard', cities: ['Graniteville'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05655', type: 'Standard', cities: ['Hyde Park'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05656', type: 'Standard', cities: ['Johnson'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05657', type: 'PO Box', cities: ['Lake Elmore'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05658', type: 'Standard', cities: ['Marshfield'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05660', type: 'Standard', cities: ['Moretown', 'South Duxbury'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05661', type: 'Standard', cities: ['Morrisville', 'Elmore', 'Morristown'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05662', type: 'PO Box', cities: ['Moscow'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05663', type: 'Standard', cities: ['Northfield', 'Riverton', 'West Berlin'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05664', type: 'PO Box', cities: ['Northfield Falls', 'Northfield Fl', 'Northfld Fls'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05665', type: 'PO Box', cities: ['North Hyde Park', 'N Hyde Park'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05666', type: 'Standard', cities: ['North Montpelier', 'N Montpelier'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05667', type: 'Standard', cities: ['Plainfield'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05669', type: 'Standard', cities: ['Roxbury', 'W Braintree', 'West Braintree'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05670', type: 'PO Box', cities: ['South Barre'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05671', type: 'Unique', cities: ['Waterbury'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05672', type: 'Standard', cities: ['Stowe'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05673', type: 'Standard', cities: ['Waitsfield'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05674', type: 'Standard', cities: ['Warren'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05675', type: 'Standard', cities: ['Washington'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05676', type: 'Standard', cities: ['Waterbury'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05677', type: 'Standard', cities: ['Waterbury Center', 'Waterbury Ctr'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05678', type: 'PO Box', cities: ['Websterville'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05679', type: 'Standard', cities: ['Williamstown'], county: 'Orange', areaCodes: ['802'] },
  { zip: '05680', type: 'Standard', cities: ['Wolcott'], county: 'Lamoille', areaCodes: ['802'] },
  { zip: '05681', type: 'Standard', cities: ['Woodbury'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05682', type: 'Standard', cities: ['Worcester', 'N Middlesex', 'North Middlesex'], county: 'Washington', areaCodes: ['802'] },
  { zip: '05701', type: 'Standard', cities: ['Rutland', 'Mendon', 'S Chittenden', 'South Chittenden'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05702', type: 'PO Box', cities: ['Rutland'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05730', type: 'Standard', cities: ['Belmont'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05731', type: 'PO Box', cities: ['Benson'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05732', type: 'Standard', cities: ['Bomoseen'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05733', type: 'Standard', cities: ['Brandon', 'Goshen', 'Leicester', 'Sudbury'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05734', type: 'Standard', cities: ['Bridport'], county: 'Addison', areaCodes: ['518', '802', '838'] },
  { zip: '05735', type: 'Standard', cities: ['Castleton'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05736', type: 'Standard', cities: ['Center Rutland', 'Ctr Rutland'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05737', type: 'Standard', cities: ['Chittenden'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05738', type: 'Standard', cities: ['Cuttingsville', 'Shrewsbury'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05739', type: 'Standard', cities: ['Danby', 'Mount Tabor'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05740', type: 'PO Box', cities: ['East Middlebury', 'E Middlebury'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05741', type: 'PO Box', cities: ['East Poultney', 'Poultney'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05742', type: 'Standard', cities: ['East Wallingford', 'E Wallingford'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05743', type: 'Standard', cities: ['Fair Haven', 'Benson', 'West Haven'], county: 'Rutland', areaCodes: ['518', '802', '838'] },
  { zip: '05744', type: 'Standard', cities: ['Florence'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05745', type: 'PO Box', cities: ['Forest Dale'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05746', type: 'PO Box', cities: ['Gaysville'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05747', type: 'Standard', cities: ['Granville'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05748', type: 'Standard', cities: ['Hancock'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05750', type: 'PO Box', cities: ['Hydeville'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05751', type: 'Standard', cities: ['Killington'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05753', type: 'Standard', cities: ['Middlebury', 'Cornwall', 'Weybridge'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05757', type: 'Standard', cities: ['Middletown Springs', 'Middletwn Spg'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05758', type: 'Standard', cities: ['Mount Holly'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05759', type: 'Standard', cities: ['North Clarendon', 'N Clarendon'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05761', type: 'Standard', cities: ['Orwell'], county: 'Addison', areaCodes: ['518', '802', '838'] },
  { zip: '05762', type: 'Standard', cities: ['Pawlet'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05763', type: 'Standard', cities: ['Pittsfield'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05764', type: 'Standard', cities: ['Pittsford', 'N Chittenden', 'North Chittenden'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05765', type: 'Standard', cities: ['Poultney'], county: 'Rutland', areaCodes: ['518', '802', '838'] },
  { zip: '05766', type: 'Standard', cities: ['Proctor'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05767', type: 'Standard', cities: ['Ripton'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05768', type: 'Standard', cities: ['Rochester'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05769', type: 'PO Box', cities: ['Rupert'], county: 'Bennington', areaCodes: ['802'] },
  { zip: '05770', type: 'Standard', cities: ['Salisbury'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05772', type: 'Standard', cities: ['Shoreham'], county: 'Addison', areaCodes: ['518', '802', '838'] },
  { zip: '05773', type: 'Standard', cities: ['Stockbridge'], county: 'Windsor', areaCodes: ['802'] },
  { zip: '05774', type: 'Standard', cities: ['Wallingford', 'Tinmouth'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05775', type: 'Standard', cities: ['Wells'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05776', type: 'Standard', cities: ['West Pawlet'], county: 'Rutland', areaCodes: ['518', '802', '838'] },
  { zip: '05777', type: 'Standard', cities: ['West Rupert'], county: 'Bennington', areaCodes: ['518', '802', '838'] },
  { zip: '05778', type: 'Standard', cities: ['West Rutland', 'Clarendn Spgs', 'Clarendon Springs'], county: 'Rutland', areaCodes: ['802'] },
  { zip: '05779', type: 'Standard', cities: ['Whiting', 'West Cornwall'], county: 'Addison', areaCodes: ['802'] },
  { zip: '05819', type: 'Standard', cities: ['Saint Johnsbury', 'St Johnsbury', 'Waterford'], county: 'Caledonia', areaCodes: ['603', '802'] },
  { zip: '05820', type: 'Standard', cities: ['Albany'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05821', type: 'Standard', cities: ['Barnet'], county: 'Caledonia', areaCodes: ['603', '802'] },
  { zip: '05822', type: 'Standard', cities: ['Barton'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05823', type: 'PO Box', cities: ['Beebe Plain'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05824', type: 'Standard', cities: ['Concord'], county: 'Essex', areaCodes: ['603', '802'] },
  { zip: '05825', type: 'PO Box', cities: ['Coventry'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05826', type: 'Standard', cities: ['Craftsbury'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05827', type: 'Standard', cities: ['Craftsbury Common', 'Craftsbry Cmn', 'Craftsbury Cm'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05828', type: 'Standard', cities: ['Danville'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05829', type: 'Standard', cities: ['Derby'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05830', type: 'Standard', cities: ['Derby Line'], county: 'Orleans', areaCodes: ['468', '802', '819', '873'] },
  { zip: '05832', type: 'Standard', cities: ['East Burke'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05833', type: 'Standard', cities: ['East Charleston', 'E Charleston'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05836', type: 'Standard', cities: ['East Hardwick'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05837', type: 'Standard', cities: ['East Haven'], county: 'Essex', areaCodes: ['802'] },
  { zip: '05838', type: 'PO Box', cities: ['East Saint Johnsbury', 'E St Johnsbry'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05839', type: 'Standard', cities: ['Glover', 'Barton'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05840', type: 'PO Box', cities: ['Granby'], county: 'Essex', areaCodes: ['802'] },
  { zip: '05841', type: 'Standard', cities: ['Greensboro'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05842', type: 'Standard', cities: ['Greensboro Bend', 'Greensbro Bnd', 'Grnsboro Bend'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05843', type: 'Standard', cities: ['Hardwick'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05845', type: 'Standard', cities: ['Irasburg'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05846', type: 'Standard', cities: ['Island Pond', 'Ferdinand'], county: 'Essex', areaCodes: ['802'] },
  { zip: '05847', type: 'Standard', cities: ['Lowell'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05848', type: 'PO Box', cities: ['Lower Waterford', 'Lwr Waterford'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05849', type: 'PO Box', cities: ['Lyndon'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05850', type: 'Standard', cities: ['Lyndon Center'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05851', type: 'Standard', cities: ['Lyndonville'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05853', type: 'Standard', cities: ['Morgan', 'Morgan Ctr'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05855', type: 'Standard', cities: ['Newport'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05857', type: 'Standard', cities: ['Newport Center', 'Newport Ctr'], county: 'Orleans', areaCodes: ['468', '802', '819', '873'] },
  { zip: '05858', type: 'Standard', cities: ['North Concord', 'Victory'], county: 'Essex', areaCodes: ['802'] },
  { zip: '05859', type: 'Standard', cities: ['North Troy', 'Jay', 'Jay Peak'], county: 'Orleans', areaCodes: ['468', '802', '819', '873'] },
  { zip: '05860', type: 'Standard', cities: ['Orleans', 'Brownington'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05861', type: 'PO Box', cities: ['Passumpsic'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05862', type: 'Standard', cities: ['Peacham'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05863', type: 'PO Box', cities: ['Saint Johnsbury Center', 'St Jhnsbry Ct'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05866', type: 'Standard', cities: ['Sheffield'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05867', type: 'Standard', cities: ['Sutton'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05868', type: 'Standard', cities: ['Troy'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05871', type: 'Standard', cities: ['West Burke'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05872', type: 'Standard', cities: ['West Charleston', 'W Charleston'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05873', type: 'Standard', cities: ['West Danville'], county: 'Caledonia', areaCodes: ['802'] },
  { zip: '05874', type: 'Standard', cities: ['Westfield'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05875', type: 'Standard', cities: ['Barton', 'West Glover'], county: 'Orleans', areaCodes: ['802'] },
  { zip: '05901', type: 'PO Box', cities: ['Averill', 'Canaan'], county: 'Essex', areaCodes: ['802'] },
  { zip: '05902', type: 'Standard', cities: ['Beecher Falls'], county: 'Essex', areaCodes: ['468', '603', '802', '819', '873'] },
  { zip: '05903', type: 'Standard', cities: ['Canaan', 'Lemington'], county: 'Essex', areaCodes: ['468', '603', '802', '819', '873'] },
  { zip: '05904', type: 'Standard', cities: ['Gilman'], county: 'Essex', areaCodes: ['603', '802'] },
  { zip: '05905', type: 'Standard', cities: ['Guildhall', 'Bloomfield', 'Brunswick', 'Maidstone'], county: 'Essex', areaCodes: ['603', '802'] },
  { zip: '05906', type: 'Standard', cities: ['Lunenburg', 'East Concord'], county: 'Essex', areaCodes: ['603', '802'] },
];

/**
 * Find zip codes by city name (case-insensitive, partial match)
 */
export function findZipCodesByCity(cityName: string): string[] {
  const cityLower = cityName.toLowerCase();
  const matching = vermontZipCodes.filter(zip =>
    zip.cities.some(city => city.toLowerCase().includes(cityLower) || cityLower.includes(city.toLowerCase()))
  );
  return matching.map(zip => zip.zip);
}

/**
 * Find zip codes by county
 */
export function findZipCodesByCounty(countyName: string): string[] {
  const countyLower = countyName.toLowerCase();
  return vermontZipCodes
    .filter(zip => zip.county.toLowerCase() === countyLower)
    .map(zip => zip.zip);
}

/**
 * Get all zip codes for a city (exact match preferred, returns ALL matches)
 */
export function getZipCodesForCity(cityName: string): string[] {
  const cityLower = cityName.toLowerCase();
  // Find ALL exact matches
  const exactMatches = vermontZipCodes.filter(zip =>
    zip.cities.some(city => city.toLowerCase() === cityLower)
  );
  if (exactMatches.length > 0) {
    return exactMatches.map(zip => zip.zip);
  }
  // Try partial match if no exact match found
  return findZipCodesByCity(cityName);
}









